### ISSUE TITLE
Issue with POST request

### ISSUE THREAD

**Issue by Cashalote** [druzsan/justetf-scraping#10]
POST request seems to have stopped working. I outputted the response to a file and did not look like a data table of correct json format. Wanted to know if something changed with API since I cannot find any news online.

**Comment by pauleonline** [comment]
Hidden-URL: https://www.justetf.com/servlet/etfs-table seems to have been moved... 404 response...

**Comment by xaver291** [comment]
Have you had the chance to take a look at this and maybe found another way around that?

**Comment by druzsan** [comment]
Hi everyone,

the overview API was indeed changed. I can see another POST request instead but unfortunately I can't replicate it from Python as straight forward as it was before. I will post here more info soon.

Any help from side is also highly appreciated!

**Comment by druzsan** [comment]
@Cashalote @pauleonline @xaver291 good news!

The current hidden URL for POST requests looks like `https://www.justetf.com/en/search.html?2-1.0-container-tabsContentContainer-tabsContentRepeater-1-container-content-etfsTablePanel=&search=ETFS&_wicket=1` where `2` in `2-1.0` could be apparently replaced with any other number dynamically. So one has to first request the `https://www.justetf.com/en/search.html` page, then parse it for the currently allowed hidden URL and then make a POST request.

I could replicate it in Python, so I have to test it a little bit and then I will build it into the project.

**Comment by druzsan** [comment]
This issue should be fixed by now.

**Comment by xaver291** [comment]
Thank you very much.

**Comment by pauleonline** [comment]
Hi Alex, thank you very much for the quick fix , ... you rock ! Christoph
